# Traefik configuration for local development
global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
    watch: true
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# Enable ping for health checks
ping: {}

# Logging
log:
  level: INFO
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log
  format: json

# Metrics
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true

# HTTP Configuration
http:
  middlewares:
    # CORS middleware for API endpoints
    api-cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "http://localhost"
          - "http://localhost:3000"
          - "http://127.0.0.1"
          - "http://127.0.0.1:3000"
        accessControlMaxAge: 100
        addVaryHeader: true

    # CORS middleware for Auth endpoints
    auth-cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "http://localhost"
          - "http://localhost:3000"
          - "http://127.0.0.1"
          - "http://127.0.0.1:3000"
        accessControlMaxAge: 100
        addVaryHeader: true

    # CORS middleware for Storage endpoints
    storage-cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "http://localhost"
          - "http://localhost:3000"
          - "http://127.0.0.1"
          - "http://127.0.0.1:3000"
        accessControlMaxAge: 100
        addVaryHeader: true

    # CORS middleware for Functions endpoints
    functions-cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "http://localhost"
          - "http://localhost:3000"
          - "http://127.0.0.1"
          - "http://127.0.0.1:3000"
        accessControlMaxAge: 100
        addVaryHeader: true

    # Security headers
    secure-headers:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
          server: ""
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customFrameOptionsValue: "SAMEORIGIN"
        contentTypeNosniff: true
        browserXssFilter: true

    # Rate limiting
    rate-limit:
      rateLimit:
        average: 100
        burst: 200
        period: 1m

    # Compression
    compression:
      compress: {}