# Traefik configuration for local development
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik

# Enable ping for health checks
ping: {}

# Logging
log:
  level: INFO
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log

# Metrics
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true