// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yptbntyathrtnmgfotjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwdGJudHlhdGhydG5tZ2ZvdGpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODc3MzksImV4cCI6MjA2Mzg2MzczOX0.zVwMo3fyirppLjgblyGWWbdjS5KKXJJmgy0sBY__w3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);